steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'pusercf'
      apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
      org: 'referenceapps_deploymenttest'
      space: 'CI-CD'
